name: client_dart # Pas de tiret, utilisez un underscore
description: Un client Dart pour l'API de gestion
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^0.13.4
  intl: ^0.18.1